# Generated by Django 4.1.5 on 2024-01-24 13:33

import apps.project_setup.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSetup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_color', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary_color', models.CharField(blank=True, max_length=255, null=True)),
                ('color_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255, null=True), size=None)),
                ('lang', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.project_setup.models.logo_photo_file_path)),
                ('login_photo', models.ImageField(blank=True, null=True, upload_to=apps.project_setup.models.login_photo_file_path)),
                ('domain_name', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_email', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_type', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_en', models.CharField(blank=True, max_length=255, null=True)),
                ('front_data', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('primary', models.CharField(blank=True, max_length=255, null=True)),
                ('secondary', models.CharField(blank=True, max_length=255, null=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('surface', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.CharField(blank=True, max_length=255, null=True)),
                ('success', models.CharField(blank=True, max_length=255, null=True)),
                ('warning', models.CharField(blank=True, max_length=255, null=True)),
                ('dark', models.BooleanField(default=False)),
            ],
        ),
    ]
